### ISSUE TITLE
Update repo to use StatefulSets

### ISSUE THREAD

**Issue by hekike** [softputer/kubernetes-redis-cluster#1]
Do you plan to update this repo to the latest StatefulSets?

http://kubernetes.io/docs/concepts/abstractions/controllers/statefulsets/

**Comment by softputer** [comment]
Thanks for your attention, I have updated this repo to StatefulSet based on the following website:
http://kubernetes.io/docs/tasks/manage-stateful-set/upgrade-pet-set-to-stateful-set/

**Comment by hekike** [comment]
@softputer wow, it was fast, thanks!
